kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

#TODO: Is this needed?
namespace: ping-cloud

resources:
  - custom-resources

#patchesStrategicMerge:
#  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
#  - custom-patches.yaml