kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ${PING_CLOUD_NAMESPACE}

resources:
  - ../base
  - custom-resources  #TODO: test this

helmCharts:
  - name: p1as-beluga-tools
    additionalValuesFiles:
      - ../../values.yaml   # base values.yaml
      - ../../values-${REGION_NICK_NAME}.yaml   # regional values.yaml
      - values.yaml   # app specific values.yaml
    includeCRDs: true
    # TODO: figure out how this is being set
    version: 19.0.0-PDO-5435-region-values-yaml
    repo: oci://${ECR_REGISTRY_NAME}/p1as-beluga-tools

# TODO: figure this out
#patchesStrategicMerge:
#  ### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###
#  - custom-patches.yaml

# TODO: figure this out
#configMapGenerator:
#  - name: last-update-reason
#    literals:
#      - UPDATE_REASON="seal non-base64 secrets"