kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../base/pingcommon

generatorOptions:
  disableNameSuffixHash: false

patchesStrategicMerge:

### Remove unneccessary MyPing pods
- ../../base/pingcommon/my-ping/remove-oauth-service.yaml
- ../../base/pingcommon/my-ping/remove-pingone-configurator.yaml

configMapGenerator:
# PingCloud services
# Pingcloud-metadata
- name: pingcloud-metadata-environment-variables
  behavior: merge
  envs:
  - ../../base/env_vars
  - ../env_vars

# Pingcloud-healthcheck
- name: pingcloud-healthcheck-environment-variables
  namespace: ${PING_CLOUD_NAMESPACE}
  behavior: merge
  envs:
  - ../../base/env_vars
  - ../env_vars

# PingCloud BOM service
- name: p14c-bom-service-environment-variables
  behavior: merge
  envs:
    - ../../base/env_vars
    - ../env_vars

# PingCloud P14C bootstrap
- name: pingcloud-p14c-bootstrap-environment-variables
  behavior: merge
  envs:
    - ../../base/env_vars
    - ../env_vars
