apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${TENANT_NAME}-${REGION_NICK_NAME}"
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        revision: ${CLUSTER_STATE_REPO_BRANCH}
        directories:
          - path: k8s-configs/${REGION_NICK_NAME}/*
          - path: k8s-configs/${REGION_NICK_NAME}/custom-resources
            exclude: true
          - path: k8s-configs/${REGION_NICK_NAME}/logging
            exclude: true
  template:
    metadata:
      name: "'{{path.basename}}'-${REGION_NICK_NAME}"
    spec:
      project: default
      source:
        repoURL: ${CLUSTER_STATE_REPO_URL}
        targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
        path: '{{path}}'
        plugin:
          name: git-ops-command
      destination:
        server: https://kubernetes.default.svc
      ignoreDifferences:
      - group: batch
        kind: Job
        jsonPointers:
        - /spec/ttlSecondsAfterFinished
      syncPolicy:
        automated:
          prune: true