apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcloud-radsecproxy
  namespace: ping-cloud
$patch: delete

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radsecproxy-ingress
$patch: delete

---
apiVersion: v1
kind: Service
metadata:
  name: radsecproxy
  labels:
    role: radsecproxy
$patch: delete
