#
# This defines the pingcloud-radsecproxy deployment.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcloud-radsecproxy
  labels:
    role: pingcloud-radsecproxy
spec:
  selector:
    matchLabels:
      role: pingcloud-radsecproxy
  template:
    metadata:
      name: pingcloud-radsecproxy
      labels:
        role: pingcloud-radsecproxy
    spec:
      serviceAccount: pingcloud-radsecproxy-serviceaccount
      initContainers:
        - name: wait-for-tls-secret
          securityContext:
            privileged: false
            runAsGroup: 2000
            runAsUser: 1000
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          image: public.ecr.aws/r2h3l6e4/bitnami/kubectl:1.15.3
          command: [ "/bin/sh", "-c" ]
          args: [while ! kubectl get secret $(SECRET_NAME); do echo "Waiting for secret $(SECRET_NAME). CTRL-C to exit."; sleep 5; done]
          env:
            - name: "WAIT_TIMEOUT_SEC"
              value: "300"
            - name: "JOB_NAME"
              value: "wait-for-tls-secret"
            - name: "SECRET_NAME"
              value: "acme-tls-cert"
      containers:
      - name: pingcloud-radsecproxy
        image: public.ecr.aws/r2h3l6e4/radiusproxy/grp:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: pingcloud-radsecproxy-environment-variables
        volumeMounts:
          - name: acme-tls-cert
            mountPath: /usr/local/secrets/certs
            readOnly: true
        resources:
          limits:
            memory: "500Mi"
            cpu: "400m"
          requests:
            memory: "200Mi"
            cpu: "200m"
        readinessProbe:
          tcpSocket:
            port: 2083
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 2083
          initialDelaySeconds: 15
          periodSeconds: 20
          failureThreshold: 3
          successThreshold: 1
          timeoutSeconds: 3
        ports:
        - containerPort: 2083
      volumes:
        - name: acme-tls-cert
          secret:
            secretName: acme-tls-cert
            optional: true
            defaultMode: 0400
